# Configuration options for your blog - customise to taste
# This file contains no secret information, so can be stored in source control (unlike database.yml)
title: Accedie
url:   http://accedie.com
author:
  name:    Lucas Hansen        # For copyright notice and ATOM feeds
  email:   lucashansen@gmail.com # Exception emails will go here, and it is used in ATOM feeds
  open_id:                  # These are used to login to the admin area
      - http://accedie.com